{% set name = "axopy" %}
{% set version = "0.2.1" %}
{% set sha256 = "b8cae78bc78d63c6d830aa592ea4930e4c72643beb5469c00ddc663ecdec65e8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy
    - scipy
    - pandas
    - h5py
    - pyqt>=5
    - pyqtgraph>=0.10

test:
  imports:
    - axopy.features
    - axopy.gui
    - axopy.pipeline
    - axopy.task
    - axopy.daq
    - axopy.design
    - axopy.experiment
    - axopy.messaging
    - axopy.storage
    - axopy.timing
    - axopy.util

about:
  home: http://github.com/axopy/axopy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Human-computer interface experimentation library'

  doc_url: http://axopy.readthedocs.io/
  dev_url: https://github.com/axopy/axopy

extra:
  recipe-maintainers:
    - ixjlyons
