travis:
  secure:
    BINSTAR_TOKEN: XvHzPGsdSbTV+P/fTcPCD2GVJNUfo3sqDTdK3vBRH07cA/xNlBMod9CazGiQX7mUzHlxYI8hv9DXZ50AakBy4IuDVNkMuMWJlY7D4Yua9zi48eoNSGcu3z5RBgN5oF2EvUU3yUj9Jvg5Vg2zDLHaoe4QRCPsJb6+uYecFOaJNaEaxGIFBxOug5w6XaqzmxB1VIIGwViWy4JjzIyUQ6gd6zuOrjkTyrL0uwylosKG8Zu1kstNoco5cGFjFh79YQ93hKsbnq82WaXPPDFTm7hBVFGGXul2KeFMrV26bw3Xk8ZOrAIP7p+pgM4+niPTS93SGwR5P37o4xI6oxG2ADd9lml6ipwL8BRaEwkGF3oEKdaAePhsK98uTIUwldWr3R8tadnLUMx9QpJwstkuwOcTBWWBs0jdKxtD6m1DH7j2X0HhutfjyAgAmgdU/c/srpqzHy/O4xqaggH4G4sDj3SRlOuMpQ+As58wDy046p74NEYAWQmACebS8Vy/s+E+4ZQYbFv9NMLSaEOqgrTJ+t5QGX7Yg7ICD09fhRF3E/2lweJHU3aoY+w2g3/kAv53ReEJavzynQbr4AXmR4XuftlkDeVEKCzyqWtu0AxiAf0Q0N/H90uFXCxMJtV54ZFwRA4gZdEc41Ig2QrVPZ2l0K3cCGWDaY/xMmrcKJZVq99p/zg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
