travis:
  secure:
    BINSTAR_TOKEN: hpk4IyM+aUB7kqTxVauz67TRKwN71qVONRrPWyDdAKUkm4ZngWa5rNidELQhRBmD0LuDRaVCwJqrlgGFUdsAHBFZUsAEWcfJVa4dR2JUimwzGTCUt6iyNtW/RzB4zdDq7MvNnfpQztks/uHZFX28Pmgd90vef5wN/8UqmSXJpJf9M9s8m8OMxMiGg7pSV0pAN9K9NwlI6pHFBg6V44U50GI/01q+fm3BG/pA8QQhSTa4DN081E5RRJFZvO5pnFp6sJg4O54dHOY6l5RXgXGDra07c6rFYt+zzam6vFT5FAjetZ9qiEb+xiBfTA7D76l4WDXKKVpMG4A30bTrjE5wyold5pmOMbagUVVF247GHWWgPL7TeUIttbAK7vCGRhFrgDsmE6fna0c48JDqF9jxc3w3L5xILf2PWBSROW9hNqiWkP7nxxkFW4Ja6bcKTxf1GiB3WkLL7Y84gXCrlzdHCKppG0UvcHxY+TuXQIn+L7e6WWmGOiNxlizyk3UAaZpRY0hzh26SvTX9+C25gmdZNc2pj9IJxW1iXVOqOBbVoqwBuIm77hpRcLnz26fs8aYYgAvYRGQviI1YqLPkVeOQTM7ligmnF76YwBEyZMVatbd//z4AWegH01MJ0k5g72IIJlPfxSQ2tkWbo1xeoFRoXUws3/ZyXYuw1j1rdCgirTY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
